### ISSUE TITLE
Vision is not a constructor

### ISSUE THREAD

**Issue by bpkennedy** [googleapis/nodejs-vision#272]
I'm using the current release, and tried:

```
const {Vision} = require('@google-cloud/vision');

const token = {} //json for the google application credential

const vision = new Vision(token);
```

But it yields error that vision is not a constructor.  What am I missing?

**Comment by bpkennedy** [comment]
Ah, I inspected the ImageAnnotatorClient export and see where the credential can be passed in as an option of that class constructor:

```
  /**
   * Construct an instance of ImageAnnotatorClient.
   *
   * @param {object} [options] - The configuration object. See the subsequent
   *   parameters for more details.
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://developers.google.com/identity/protocols/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {function} [options.promise] - Custom promise module to use instead
   *     of native Promises.
   * @param {string} [options.servicePath] - The domain name of the
   *     API remote host.
   */
```
So, I implemented as thus which seems to work fine:

```
import Vision from '@google-cloud/vision';

new Vision.ImageAnnotatorClient({
    credentials: token
  });
```

This seems to work fine, but it does go against [some documentation I read earlier](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually) (see the *Passing the path to the service account key in code*).  It describes:

```
// Imports the Google Cloud client library.
const {Storage} = require('@google-cloud/storage');

// Instantiates a client. Explicitly use service account credentials by
// specifying the private key file. All clients in google-cloud-node have this
// helper, see https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/docs/authentication.md
const storage = new Storage({
  projectId: 'project-id',
  keyFilename: '/path/to/keyfile.json'
});
```

Event though it describes the storage API, I took this to mean that vision also accepts a credential object passed to the default export of the library just like storage, which is not the case and had me confused.

**Comment by stephenplusplus** [comment]
@JustinBeckwith could we make that promise true?:

> All clients in google-cloud-node have this helper, see https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/docs/authentication.md

Practically speaking, that would mean:

```diff
- new Vision.ImageAnnotatorClient();
+ new Vision();
```

**Comment by kinwa91** [comment]
This is more of a discussion on import syntax for generated libraries. Perhaps open an issue on `gapic-generator` or `google-cloud-node` if we think it deserves further discussion?

To make things clear, @bpkennedy, this is how you would import vision:

```json
const visionModule = require('@google-cloud/vision');
const client = new visionModule.ImageAnnotatorClient();
// OR
const client = new visionModule.ProductSearchClient();
```

**Comment by JamesVanWaza** [comment]
I am still receiving this error. While trying to do the example for - https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/index.html?index=..%2F..index#8 I Copied and pasted everything and got the following error 

<img width="962" alt="Screen Shot 2020-07-16 at 6 49 07 PM" src="https://user-images.githubusercontent.com/4000076/87730169-08ce1700-c795-11ea-9b65-ff0a79e85802.png">
<img width="974" alt="Screen Shot 2020-07-16 at 6 49 23 PM" src="https://user-images.githubusercontent.com/4000076/87730191-12f01580-c795-11ea-9f81-e66b5a0f463f.png">

#### Environment details

  - OS: 10.15.5
  - Node.js version: 12.16.3
  - npm version: 6.14.4
  - `@google-cloud/vision` version: 2.1.1

**Comment by alexander-fenster** [comment]
@JamesVanWaza Thank you for pointing out the bad example. We'll fix it. For now, please make sure you construct individual clients (`new Vision. ImageAnnotatorClient()`, `new Vision.ProductSearchClient()`) instead of `new Vision()`.

**Comment by JamesVanWaza** [comment]
@alexander-fenster also once it's fixed, please request an update to https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/index.html?index=..%2F..index#8 so I can see an example of how its done.

**Comment by alexander-fenster** [comment]
@bcoe @JustinBeckwith FYI - the codelab example is out of date

**Comment by JamesVanWaza** [comment]
@alexander-fenster @bcoe @JustinBeckwith the codelab was updated as of October 22, 2020. But the error is still showing.

**Comment by dknopf** [comment]
@bpkennedy thank you so much for posting this, I was struggling with vision API authentication for days. The documentation for authenticating client libraries absolutely needs to include the explicit passing of credentials via code, only mentioning setting the credentials via environment variable is hugely confusing when that solution doesn't work for cloud functions, because there isn't even a mention that you can explicitly pass in the credentials to an API like Vision.

**Comment by JamesVanWaza** [comment]
@alexander-fenster @bcoe @JustinBeckwith the codelab was updated as of October 22, 2020. But the error is still showing. is there a way we can do a pull request for the codelab?

**Comment by JustinBeckwith** [comment]
@JamesVanWaza if you're running into trouble, please file a new issue with the example of the code you're trying, and the specific error message you're getting :)

**Comment by JamesVanWaza** [comment]
@JustinBeckwith 
The https://firebase.google.com/codelabs/firebase-cloud-functions?index=..%2F..index#8 is still showing `new.vision()` instead of `const client = new visionModule.ProductSearchClient();` are you able to update that?

**Comment by JustinBeckwith** [comment]
The tutorial, which is very separate from this library, has a [report a mistake](https://github.com/firebase/friendlychat-web/issues) link.  I would suggest posting an issue over there!  Feel free to reference this one.

**Comment by JamesVanWaza** [comment]
Looks like multiple issues have been reported there. Let your teammates know. :smile:
